sudo: required

env:
  - DOCKER_COMPOSE_REPO=https://github.com/docker/compose/releases/download
  - DOCKER_COMPOSE_VERSION=1.22.0

services:
  - docker

before_install:
  # Replace the pre-installed Docker Compose version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L ${DOCKER_COMPOSE_REPO}/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Build an image for running tests
  - docker-compose build app

script:
  # Run a container for testing
  - docker container run -e NODE_ENV=test --name playground-test --rm local/playground:development test:coverage
