sudo: required

language: node_js

node_js:
  - 10.11.0

cache:
  directories:
    - node_modules

env:
  global:
    - CI_BINARY_PATH=/usr/local/bin
    - CI_BUILD_ZIP=build.zip
    - CI_CONTAINER_WORKDIR=/usr/src/app
    - CI_LCOV_DATA=./coverage/lcov.info
    - CI_SCRIPTS_PATH=./scripts/ci
    - DOCKER_COMPOSE_REPO=https://github.com/docker/compose/releases/download
    - DOCKER_COMPOSE_VERSION=1.22.0

addons:
  apt:
    packages:
      # Update to the latest version of Docker Community Edition
      - docker-ce

services:
  - docker

before_install:
  # Install additional dependencies required for running on the CI environment
  - make ci-update

script:
  # Run tests and create code coverage reports
  - make ci-test

deploy:
  # Create deployment configuration and build a production image
  - provider: script
    script: make ci-deploy
    on:
      branch: master
  # Deploy to a production server 1 (Heroku)
  - provider: heroku
    app:
      master: docker-playground-react
    api_key:
      secure: ${HEROKU_API_KEY}
  # Deploy to a production server 2 (AWS Elastic Beanstalk)
  - provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker-playground"
    env: "docker-playground-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-413973540256"
    bucket_path: "docker-playground"
    skip_cleanup: true
    zip_file: ${CI_BUILD_ZIP}
    on:
      branch: master
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key:
      secure: ${AWS_SECRET_KEY}

after_script:
  # Send LCOV data to coveralls.io
  - cat ${CI_LCOV_DATA} | coveralls
  # List images and containers
  - docker image ls
  - docker container ls -a
