sudo: required

language: node_js

node_js:
  - 10.11.0

cache:
  directories:
    - node_modules

env:
  global:
    - BINARY_PATH=/usr/local/bin
    - BUILD_ZIP=build.zip
    - DOCKER_COMPOSE_REPO=https://github.com/docker/compose/releases/download
    - DOCKER_COMPOSE_VERSION=1.22.0
    - LCOV_DATA=./coverage/lcov.info
    - SCRIPTS_PATH=./scripts/ci

addons:
  apt:
    packages:
      # Update to the latest version of Docker Community Edition
      - docker-ce

services:
  - docker

before_install:
  # Install additional dependencies required for running on the CI environment
  - make ci-update

before_script:
  # Setup the CI environment and install required dependencies
  - make ci-setup

script:
  # Run tests and generate code coverage reports
  - make ci-test

after_success:
  # Create code coverage reports (LCOV format)
  - make ci-coverage

deploy:
  # Create deployment configuration and build a production image
  - provider: script
    script: make ci-deploy
    on:
      branch: master
    skip_cleanup: true
  # Deploy to a production server 1 (Heroku)
  - provider: heroku
    app:
      master: docker-playground-react
    api_key:
      secure: ${HEROKU_API_KEY}
    skip_cleanup: true
  # Deploy to a production server 2 (AWS Elastic Beanstalk)
  - provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker-playground"
    env: "docker-playground-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-413973540256"
    bucket_path: "docker-playground"
    skip_cleanup: true
    zip_file: ${BUILD_ZIP}
    on:
      branch: master
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key:
      secure: ${AWS_SECRET_KEY}

after_script:
  # Send LCOV data to coveralls.io
  - make ci-coveralls
  # List images and containers
  - docker image ls -a
  - docker container ls -a
  - docker network ls
  - docker volume ls
  - ls
  # Cleanup
  - make ci-clean
  - docker image ls -a
  - docker container ls -a
  - docker network ls
  - docker volume ls
  - ls

notifications:
  # Default email notification settings
  email:
    on_success: change
    on_failure: always
  # Send notifications to Slack channels about build results
  slack:
    rooms:
      - secure: "hs+eOloJTwJniTLoac740Bka6feXA7ud+ZSVaG2n0qV/3B3mOOL/MXmZGbTHOKP4dOGdEzGfM4UU7aRcZTcMUeGZbIURrT97yn3CgiUJeWJNL6RpvRjmYVL3T44dJTDjRPnFyJEL/mLTbyLC3yw9+yf1aKTo/T2d2oja5a2g1tKWsTyDcXxs15jPz4dIBMgTE/oBFjOc/KQYs2O7IanJgOUXW515QwCjXO/hp3kPqefpYflywoQCyBFsoeAjlMvCE9HiMLr0wRv+rTWdeymbfRQ9BpseulDxK3Z8tTiquugcOsLCOYZ5IpWDGhLL4euWMRJK6P6XYWSwx4XbGKnBiYbD9uiO8L+UebZTTa1XOfI1tDaHlEpc9eDvlxV/qAzJ8uKUZ+Fq38DnBA6eAUEikBu7W1ScuIBZD35TosOaXWQiBAmmIL463uyI7y8vHStrKAlfnPbA5/5X9vIRuzPiuFPeYLoUgdZoIcVQ2KEtkrQrIhDMHvxf0RVGdfTW3+b2c9MPjL+NurCvKxIGXggF/613cMyBEVbrlFq49teBzdxQP44+vB2NVapKM1rkeHUGQeuZKNm9r2AjiTDzow9MmXOOMjbNDV+lfuSr9t7U6K0qxLSR+E3duplL25fNAUKr4Ab19oyT0KIucihmnJXVrLdrJY+tPsb0gaKXwp5OW9M="
    on_success: always
    on_failure: always
