sudo: required

language: node_js

node_js:
  - 10.11.0

cache:
  directories:
    - node_modules

env:
  global:
    - BUILD_VERSION=0.0.7
    - BUILD_ZIP=build.zip
    - DOCKER_COMPOSE_REPO=https://github.com/docker/compose/releases/download
    - DOCKER_COMPOSE_VERSION=1.22.0

addons:
  apt:
    packages:
      # Upgrade to the latest version of Docker Community Edition
      - docker-ce

services:
  - docker

before_install:
  # Upgrade Docker Compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L ${DOCKER_COMPOSE_REPO}/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  # Run a container for testing, run tests, and generate a coverage report
  - echo $TRAVIS_BUILD_DIR
  - pwd
  - ls
  # The following legacy script works
  # - yarn test:coverage
  # Running coverage testing in a container
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up
  - docker image ls
  - docker container ls -a
  # Copy
  - docker cp app-ci:/usr/src/app/coverage ./
  - cat $PWD/coverage/lcov.info
  - yarn replace 'SF:/usr/src/app' 'SF:/home/travis/build/[secure]/docker-playground' ./coverage/lcov.info
  # Logs
  - ls
  - cd coverage
  - ls
  - pwd
  - stat --format '%a' lcov.info
  - sudo chmod 664 lcov.info
  - stat --format '%a' lcov.info
  - cd ..
  - pwd
  - echo $PWD
  - ls $PWD/coverage
  # Coveralls, it works without credential and node_modules path
  - cat $PWD/coverage/lcov.info
  # - stat --format '%a' $PWD/coverage/lcov.info
  - cat $PWD/coverage/lcov.info | coveralls
  - ls ./coverage
  - ls
  # - rm -rf ./coverage
  - ls

deploy:
  # Create deployment configuration and build a production image
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master
  # Deploy to a production server 1 (Heroku)
  - provider: heroku
    app:
      master: docker-playground-react
    api_key:
      secure: $HEROKU_API_KEY
  # Deploy to a production server 2 (AWS Elastic Beanstalk)
  - provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker-playground"
    env: "docker-playground-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-413973540256"
    bucket_path: "docker-playground"
    skip_cleanup: true
    zip_file: ${BUILD_ZIP}
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"

after_script:
  # - pwd
  # - ls
  # The following script works
  # - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN cat ./coverage/lcov.info | node node_modules/.bin/coveralls
  # - cd coverage
  # - ls
  # - cd / && pwd
  # - cd ~/ && pwd
  # Clean up Docker
  - docker-compose down
  - docker image rm app:ci
  - docker image ls
  - docker container ls -a
