sudo: required

language: node_js

node_js:
  - 10.11.0

cache:
  directories:
    - node_modules

env:
  global:
    - BINARY_PATH=/usr/local/bin
    - BUILD_REPO=rxseven/playground
    - BUILD_VERSION=0.0.9
    - BUILD_ZIP=build.zip
    - CONTAINER_WORKDIR=/usr/src/app
    - DOCKER_COMPOSE_REPO=https://github.com/docker/compose/releases/download
    - DOCKER_COMPOSE_VERSION=1.22.0
    - LCOV_DATA=./coverage/lcov.info
    - PRODUCTION_CONFIG=Dockerrun.aws.json
    - SCRIPTS_PATH=./scripts/ci

addons:
  apt:
    packages:
      # Update to the latest version of Docker Community Edition
      - docker-ce

services:
  - docker

before_install:
  # Install additional dependencies required for running on the CI environment
  - make ci-update

script:
  # Run tests and create code coverage reports
  - make ci-test

deploy:
  # Create deployment configuration and build a production image
  - provider: script
    script: ${SCRIPTS_PATH}/deploy.sh
    on:
      branch: master
  # Deploy to a production server 1 (Heroku)
  - provider: heroku
    app:
      master: docker-playground-react
    api_key:
      secure: ${HEROKU_API_KEY}
  # Deploy to a production server 2 (AWS Elastic Beanstalk)
  - provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "docker-playground"
    env: "docker-playground-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-413973540256"
    bucket_path: "docker-playground"
    skip_cleanup: true
    zip_file: ${BUILD_ZIP}
    on:
      branch: master
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key:
      secure: ${AWS_SECRET_KEY}

after_script:
  # Send LCOV data to coveralls.io
  - cat ${LCOV_DATA} | coveralls
  # List images and containers
  - docker image ls
  - docker container ls -a
  # Playground
  - cat Dockerrun.aws.json
  - sed -i='' "s/<IMAGE_REPO>/${BUILD_REPO}/" ${PRODUCTION_CONFIG}
  - sed -i='' "s/<IMAGE_TAG>/${BUILD_VERSION}/" ${PRODUCTION_CONFIG}
  - cat Dockerrun.aws.json
