version: "3.7"

services:
  proxy:
    image: ${IMAGE_BASE_PROXY}
    ports:
      - ${PORT_MAPPING_DEFAULT}
      - ${PORT_MAPPING_SSL}
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: true
      - type: bind
        source: ${CONFIG_PROXY}/certs
        target: ${PROXY_CONFIG_CONTAINER}}/certs
  app:
    build:
      args:
        BASE_NODE: ${IMAGE_BASE_NODE}
        PORT_EXPOSE: ${PORT_EXPOSE_APP}
        WORKDIR: ${CONTAINER_WORKDIR}
      context: .
      dockerfile: Dockerfile
    container_name: ${IMAGE_REPO}
    image: "${IMAGE_USERNAME}/${IMAGE_REPO}:${RELEASE_VERSION}"
