version: "3.7"

services:
  proxy:
    container_name: "${IMAGE_REPO}-proxy"
  app:
    build:
      args:
        BASE_NGINX: ${IMAGE_BASE_NGINX}
        BUILD_RELEASE_DATE: ${RELEASE_DATE}
        BUILD_RELEASE_VERSION: ${RELEASE_VERSION}
        PROXY_HOST: ${PROXY_HOST}
        LABEL_AUTHOR_EMAIL: ${AUTHOR_EMAIL}
        LABEL_AUTHOR_NAME: ${AUTHOR_NAME}
        LABEL_DESCRIPTION: ${IMAGE_DESCRIPTION}
        LABEL_LICENSE: ${IMAGE_LICENSE}
        LABEL_INTERMEDIATE: ${IMAGE_LABEL_INTERMEDIATE}
        PORT_EXPOSE: ${PORT_EXPOSE_PROXY}
      dockerfile: Dockerfile.production
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: ${APP_DOMAIN}
      VIRTUAL_PORT: ${PORT_EXPOSE_PROXY}
    restart: always
