version: "3.7"

services:
  app:
    build:
      args:
        BUILD_RELEASE_DATE: ${IMAGE_RELEASE_DATE}
        BUILD_RELEASE_VERSION: ${IMAGE_TAG}
        NGINX_VERSION: ${IMAGE_BASE_NGINX}
      dockerfile: Dockerfile.production
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    restart: always

