version: "3.7"

services:
  app:
    command: test:coverage
    container_name: ${CONTAINER_NAME_CI}
    environment:
      CI: "true"
      NODE_ENV: test
    image: "${ENV_CI}/${IMAGE_REPO}:${RELEASE_VERSION}"
