version: "3.7"

services:
  proxy:
    container_name: "${IMAGE_REPO}-${SUFFIX_LOCAL}-${SUFFIX_PROXY}"
  app:
    build:
      args:
        PACKAGE_GLIBC_VERSION: ${PACKAGE_GLIBC_VERSION}
    container_name: "${IMAGE_REPO}-${SUFFIX_LOCAL}"
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: ${APP_DOMAIN}.${HOST_TLD}
      VIRTUAL_PORT: ${PORT_EXPOSE_APP}
    image: "${ENV_LOCAL}/${IMAGE_REPO}"
    volumes:
      - type: bind
        source: .
        target: ${CONTAINER_WORKDIR}
      - type: volume
        source: ${DIR_DEPENDENCIES}
        target: "${CONTAINER_WORKDIR}/${DIR_DEPENDENCIES}"
  githooks:
    build:
      args:
        BUSYBOX_VERSION: ${IMAGE_BASE_BUSYBOX}
      context: .
      dockerfile: Dockerfile.githooks
      target: githooks
    container_name: "${IMAGE_REPO}-githooks"
    image: "${ENV_LOCAL}/${IMAGE_REPO}:githooks"
    volumes:
      - type: bind
        source: ./.git/hooks
        target: /tmp/.git/hooks
      - type: bind
        source: ./hooks
        target: /tmp/hooks

volumes:
  node_modules:
