version: "3.7"

services:
  proxy:
    container_name: "${IMAGE_REPO}-${CONTAINER_SUFFIX_LOCAL}-${CONTAINER_SUFFIX_PROXY}"
  app:
    container_name: "${IMAGE_REPO}-${CONTAINER_SUFFIX_LOCAL}"
    environment:
      NODE_ENV: development
      VIRTUAL_HOST: ${APP_DOMAIN}.${APP_TLD}
      VIRTUAL_PORT: ${PORT_EXPOSE_APP}
    image: "${IMAGE_LOCAL}/${IMAGE_REPO}"
    volumes:
      - type: bind
        source: .
        target: ${WORKDIR}
      - type: volume
        source: ${DIR_DEPENDENCIES}
        target: "${WORKDIR}/${DIR_DEPENDENCIES}"

volumes:
  node_modules:
