#!/bin/sh

# Husky 0.14.3
# Custom configuration v3

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}

cd "."

# Check if precommit script is defined, skip if not
has_hook_script precommit || exit 0

# Add common path where Node can be found
# Brew standard installation path /usr/local/bin
# Node standard installation path /usr/local
export PATH="$PATH:/usr/local/bin:/usr/local"

# Export Git hook params
export GIT_PARAMS="$*"

# Run pre-commit script within a container
echo "Husky : docker container run --rm local/playground:latest precommit"
echo

docker container run --rm local/playground:latest precommit || {
  echo
  echo "Husky : pre-commit hook failed (add --no-verify to bypass)"
  exit 1
}
